version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
  web:
    build: ./src
    command: sh -c "python manage.py collectstatic --no-input && python manage.py migrate && gunicorn --bind 0.0.0.0:8000 core.wsgi --workers=4"
    volumes:
      - ./src:/code
      - static_volume:/code/static/
      - media_volume:/code/media/
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db
  nginx:
    image: nginx
    restart: always
    volumes:
      - static_volume:/code/static/
      - media_volume:/code/media/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  media_volume:
  static_volume: