version: "3.9"

services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password --mysqlx=0
    volumes:
      - ./data/db:/var/lib/mysql/
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
  web:
    build: ./src
    command: sh -c "python manage.py collectstatic --no-input && python manage.py migrate && gunicorn --bind 0.0.0.0:8000 core.wsgi --workers=4"
    restart: always
    volumes:
      - ./src:/code
      - static_volume:/code/static/
      - media_volume:/code/media/
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db
    healthcheck:
      start_period: 10s
  nginx:
    image: nginx
    restart: always
    volumes:
      - static_volume:/code/static/
      - media_volume:/code/media/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  media_volume:
  static_volume:
