# Generated by Django 3.2.15 on 2022-08-16 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_auto_20220815_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя пользователя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия пользователя')),
                ('second_name',
                 models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество пользователя')),
                ('gender',
                 models.IntegerField(choices=[(0, 'Man'), (1, 'Woman')], default=0, verbose_name='Пол пользователя')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес проживания пользователя')),
                ('avatar', models.ImageField(upload_to=users.models.upload_to, verbose_name='Аватар пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь школьник',
                'verbose_name_plural': 'Пользователи школьники',
                'db_table': 'school_users',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='second_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False,
                                      help_text='Designates whether the user can log into this admin site.',
                                      verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.DeleteModel(
            name='UserAvatar',
        ),
        migrations.AddField(
            model_name='schooluser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
