# Generated by Django 3.2.15 on 2022-08-16 06:17

from django.db import migrations, models

import users.models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_auto_20220816_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooluser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.upload_to,
                                    verbose_name='Аватар пользователя'),
        ),
    ]
