# Generated by Django 3.2.15 on 2022-08-26 16:44

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220816_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя пользователя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия пользователя')),
                ('second_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество пользователя')),
                ('is_company', models.BooleanField(default=False, verbose_name='Является ли пользователь представителем компании')),
                ('company_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название компании')),
                ('description', models.TextField(verbose_name='Описание')),
                ('gender', models.IntegerField(choices=[(0, 'Man'), (1, 'Woman')], default=0, verbose_name='Пол')),
                ('contacts', models.TextField(blank=True, null=True, verbose_name='Контакты')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=users.models.upload_to, verbose_name='Аватар')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'profile_users',
            },
        ),
        migrations.RemoveField(
            model_name='employeruser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='schooluser',
            name='user',
        ),
    ]
