# Generated by Django 3.2.15 on 2022-09-07 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220826_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(verbose_name='Токен пользователя')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profileuser')),
            ],
            options={
                'verbose_name': 'Токен уведомлений пользователя',
                'verbose_name_plural': 'Токены управления пользователей',
                'db_table': 'notification_token_users',
            },
        ),
    ]
