# Generated by Django 3.2.15 on 2022-08-26 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterModelOptions(
            name='adcategory',
            options={'verbose_name': 'Категория объявления', 'verbose_name_plural': 'Категории объявлений'},
        ),
        migrations.AlterModelOptions(
            name='adphoto',
            options={'verbose_name': 'Фотография объявления', 'verbose_name_plural': 'Фотографии объявлений'},
        ),
        migrations.AlterModelOptions(
            name='adschedule',
            options={'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписания'},
        ),
    ]
