# Generated by Django 3.2.15 on 2022-08-26 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20220826_1944'),
        ('users', '0007_auto_20220826_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_ad_user', to='users.profileuser'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='users',
            field=models.ManyToManyField(related_name='users_ad_user', to='users.ProfileUser'),
        ),
    ]
