# Generated by Django 3.2.15 on 2022-08-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220826_1944'),
        ('ads', '0003_auto_20220826_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_ad_user', to='users.ProfileUser'),
        ),
    ]
