# Generated by Django 3.2.15 on 2022-08-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_ad_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='address',
            field=models.TextField(default=1, verbose_name='Адрес'),
            preserve_default=False,
        ),
    ]
